<?php
namespace app\index\controller;

use think\captcha\Captcha;
use think\Controller;
use think\Db;
use think\Request;
use think\Response;
use think\Session;
use app\index\model\User as UserModel;


class User extends Base
{
    /**
     * 初始化 处理 (构造函数)
     */

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 登陆页面
     */
    public function login()
    {
        $this->alreadyLogin();
        if (Session::get('userId') > 0) {
            $this->error('请勿重复登陆!');
        }
        return $this->fetch();
    }

    /**
     * 登陆操作
     */
    public function checkLogin(Request $request)
    {
        $data = $request->param();//获取参数

        //判断是否为空
        if (empty($data['name'])) {
            $this->error('用户账号不能为空!');
        }
        if (empty($data['password'])) {
            $this->error('密码不能为空!');
        }


        //获取验证码
        $captcha = new Captcha();
        if (!$captcha->check($data['verify'])) {
            $this->error('验证码不正确!');
        }

        $model = new \app\index\model\Admin();
        $result = $model->where(['name' => $data['name'], 'password' => $data['password'] ])->find();

        if (!$result) {
            $this->error('账号或密码错误，请重新输入!');
        }
        //删除密码
        unset($result['password']);

        //写入session
        Session::set('userId', $result['id']);
        Session::set('userName', $result['name']);
        Session::set('user_info', $model->getData());

        return Response::create(['code' => 1, 'msg' => '登录成功，点击【确定】进入~', 'data' => $result], 'JSON');

    }

    /**
     * 登出操作
     */
    public function logout()
    {
        Session::delete('userId');
        Session::delete('userName');
        Session::delete('user_info');
        $this ->success('注销登陆，正在返回','user/login');
        return Response::create(['code' => 1, 'info' => '退出成功！'], 'json');
    }

    /**
     * 手动实例化验证码
     */
    public function captcha_img()
    {
        $captcha = new Captcha();
        return $captcha->entry();
    }

    /**
     *用户管理列表
     */
    public function index()
    {
        $this->view->assign('title', '普通用户列表');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        $this->view->count = UserModel::count();

        $list =UserModel::paginate(8); //每页显示6条
        $this -> view -> assign('list', $list);

        return $this->view->fetch('admin_list');
    }
      //渲染编辑管理员界面
    public function adminEdit(Request $request)
    {
        $user_id = $request -> param('id');
        $result = UserModel::get($user_id);
        $this->view->assign('title','编辑管理员信息');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('admin_edit');
    }
    //更新数据操作
    public function editUser(Request $request)
    {
        //获取表单返回的数据
//        $data = $request -> param();
        $param = $request->param();

        //去掉表单中为空的数据,即没有修改的内容
        foreach ($param as $key => $value) {
            if (!empty($value)) {
                $data[$key] = $value;
            }
        }

        $condition = ['id' => $data['id']];
        $result = UserModel::update($data, $condition);

        //如果是admin用户,更新当前session中用户信息user_info中的角色role,供页面调用
        if (Session::get('user_info.name') == 'admin') {
            Session::set('user_info.role', $data['role']);
        }


        if (true == $result) {
            return ['status' => 1, 'message' => '更新成功'];
        } else {
            return ['status' => 0, 'message' => '更新失败,请检查'];
        }
    }

    //删除操作
    public function deleteUser(Request $request)
    {
        $user_id = $request->param('id');
        UserModel::update(['is_delete' => 1], ['id' => $user_id]);
        UserModel::destroy($user_id);

    }

    //恢复删除操作
    public function unDelete()
    {
        UserModel::update(['delete_time' => NULL], ['is_delete' => 1]);
    }

    //添加操作的界面
    public function  adminAdd()
    {
        $this->view->assign('title','添加管理员');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        return $this->view->fetch('admin_add');
    }



    //检测用户名是否可用
    public function checkUserName(Request $request)
    {
        $userName = trim($request->param('name'));
        $status = 1;
        $message = '用户名可用';
        if (UserModel::get(['name' => $userName])) {
            //如果在表中查询到该用户名
            $status = 0;
            $message = '用户名重复,请重新输入~~';
        }
        return ['status' => $status, 'message' => $message];
    }


    //检测用户邮箱是否可用
    public function checkUserEmail(Request $request)
    {
        $userEmail = trim($request->param('email'));
        $status = 1;
        $message = '邮箱可用';
        if (UserModel::get(['email' => $userEmail])) {
            //查询表中找到了该邮箱,修改返回值
            $status = 0;
            $message = '邮箱重复,请重新输入~~';
        }
        return ['status' => $status, 'message' => $message];
    }

    //添加操作
    public function save(Request $request)
    {
//
        $data=input('post.');
//        dump($data);
        $code=Db::execute("insert into user value(null,:name,:password,:realname,:email,:role,null,null,null)",$data);

        if($code){
            //跳转
            $this->success("添加成功");
        }else{
            $this->error("添加失败");
        }

    }

}
