<?php
namespace app\index\controller;
use think\Controller;
use think\Session;

class Base extends Controller
{
    private $userId = '';
    //const USER_ID = '';
    /*
     *
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        define('USER_ID', Session::get('use_id'));
        $this->userId = (int)Session::get('userId') > 0 ? (int)Session::get('userId') : 0;
    }

    protected  function isLogin()
    {
        if(empty($this->userId)){
            $this->error('用户未登录，无权访问',url('user/login'));
        }
    }

    protected function alreadyLogin()
    {
        if(!empty($this->userId)){
            $this->error('用户已经登陆，请勿重复登陆',url('index/index'));
        }

    }

    /**
     * 获取用户Id
     */
    protected function getUserId(){
        return $this->userId;
    }
}
