<?php

namespace app\web\controller;

use think\Controller;
use think\Session;

class Base extends Controller
{
    //记录用户id       还是不要用常量好点
    private $userId = '';
    //const USER_ID = '';
    /*
     *
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        define('USER_ID', Session::get('use_id'));
        $this->userId = (int)Session::get('userId') > 0 ? (int)Session::get('userId') : 0;
    }

    //你這樣寫 然後繼承那个控制器那里再掉一下 不嫌麻烦吗 _initialize 是优先执行的
    protected function isLogin()
    {
        if (empty($this->userId)) {
            $this->error('用户未登录，无权访问', url('/web'));
        }
    }


    /**
     * 获取用户Id
     */
    protected function getUserId()
    {
        return $this->userId;
    }
}