<?php
namespace app\index\controller;
use think\Controller;
use think\Session;

class Base extends Controller
{
    //记录用户id
    private $userId = '';
    //const USER_ID = '';

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userId = (int)Session::get('userId') > 0 ? (int)Session::get('userId') : 0;
    }

    /**
     * 判断用户是否登录
     */
    protected  function isLogin()
    {
        if(empty($this->userId)){
            $this->error('用户未登录，无权访问',url('topman/login'));
        }
    }


    /**
     * 防止用户重复
     */
//    防止用户重复登陆
    protected function alreadyLogin()
    {
        if(!empty($this->userId)){
            $this->error('用户已经登陆，请勿重复登陆',url('index/index'));
        }

    }

    /**
     * 获取用户Id
     */
    protected function getUserId(){
        return $this->userId;
    }
}