<?php
namespace app\index\controller;

use think\Db;




class Course extends Base
{
    /**
     * 初始化 处理 (构造函数)
     */

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 渲染秩序表列表界面
     */
    public function index()
    {
//
        $this->view->assign('title', '秩序表');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');


        $list =Db::table('course')->select();

        $this -> view -> assign('list', $list);
        //渲染秩序表列表模板
        return $this->view->fetch('course_list');
    }


}

