<?php
namespace app\index\controller;


use think\Db;


class Judgment extends Base
{
    /**
     * 初始化 处理 (构造函数)
     */

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 渲染裁判员负责项目信息界面
     */
//裁判负责项目信息
    public function index()
    {
        $this->view->assign('title', '裁判员');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        $id = session('userId');
        $list = Db::table('judgment')->where('id',$id)->select();
        $this->assign("list", $list);

        $art = session('art');
        $man = Db::table('man')->where('art1',$art)->whereOr('art2',$art)->whereOr('art3',$art)->whereOr('art4',$art)->whereOr('art5',$art)->whereOr('art6',$art)->whereOr('art7',$art)->whereOr('art8',$art)->whereOr('art9',$art)->whereOr('art10',$art)->limit(1)->select();
        $this->assign('man',$man);
        $woman = Db::table('woman')->where('art1',$art)->whereOr('art2',$art)->whereOr('art3',$art)->whereOr('art4',$art)->whereOr('art5',$art)->whereOr('art6',$art)->whereOr('art7',$art)->whereOr('art8',$art)->whereOr('art9',$art)->whereOr('art10',$art)->limit(1)->select();
        $this->assign('woman',$woman);
        $leader =  Db::table('leader')->where('art1',$art)->whereOr('art2',$art)->limit(1)->select();
        $this->assign('leader',$leader);

        //渲染管理员列表模板
        return $this->view->fetch('message_list');
    }


}

