<?php
namespace app\index\controller;


use think\Db;
use think\Request;

use app\index\model\Woman as WomanModel;




class Woman extends Base
{
    /**
     * 初始化 处理 (构造函数)
     */

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //渲染运动员列表界面
    public function index()
    {
//       //通过session('userId')查询对应数据
        $id= Request::instance()->session('userId');
        $list=Db::table('woman')->where('id',$id)->select();
        $this -> view -> assign('list', $list);

        $this->view->assign('title', '');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        return $this->view->fetch('admin_list');
    }


    //渲染运动员报名界面
    public function adminEdit(Request $request)
    {
        $user_id = $request -> param('id');
        $result = WomanModel::get($user_id);
        $this->view->assign('title','女运动员列表');
        $this->view->assign('keywords','女运动员列表');
        $this->view->assign('desc','女运动员列表');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('admin_edit');
    }


    //更新数据操作
    public function editUser(Request $request)
    {

        $param = $request->param();

        //去掉表单中为空的数据,即没有修改的内容
        foreach ($param as $key => $value) {
            if (!empty($value)) {
                $data[$key] = $value;
            }
        }

        $condition = ['id' => $data['id']];
        $result = WomanModel::update($data, $condition);



        if (true == $result) {
            return ['status' => 1, 'message' => '成功'];
        } else {
            return ['status' => 0, 'message' => '失败,请检查'];
        }
    }


//个人成绩查询
    public function search(){
        $this->view->assign('title','查询结果');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');

        //通过session('userId')查询对应数据
        $id= Request::instance()->session('userId');
        $list=Db::table('woman')->where('id',$id)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('search_list');
    }

    //个人信息
    public function message(){
        $this->view->assign('title','个人信息');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');

        //通过session('userId')查询对应数据
        $id= Request::instance()->session('userId');
        $list=Db::table('woman')->where('id',$id)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('message_list');
    }

    //修改个人信息界面
    public function messageEdit(Request $request)
    {
        $user_id = $request -> param('id');
        $result = WomanModel::get($user_id);
        $this->view->assign('title','个人信息修改');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('message_edit');
    }

    //比赛项目规则界面
    public function rule()
    {
        $this->view->assign('title','比赛项目规则说明');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        return $this->view->fetch('rule');
    }

    //个人参赛信息界面
    public function matchMessage()
    {
        $this->view->assign('title','个人参赛信息');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        //通过session('userId')查询对应数据
        $id= Request::instance()->session('userId');
        $list=Db::table('woman')->where('id',$id)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('matchMessage');
    }

    //女子项目赛程表
    public function time()
    {
        $this->view->assign('title','男子比赛赛程表');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list1=Db::table('woman')->where('art1','100米')->limit(1)->select();
        $this -> view -> assign('list1', $list1);

        $list2=Db::table('woman')->where('art2','200米')->limit(1)->select();
        $this -> view -> assign('list2', $list2);

        $list3=Db::table('woman')->where('art3','400米')->limit(1)->select();
        $this -> view -> assign('list3', $list3);

        $list4=Db::table('woman')->where('art4','800米')->limit(1)->select();
        $this -> view -> assign('list4', $list4);

        $list5=Db::table('woman')->where('art5','1500米')->limit(1)->select();
        $this -> view -> assign('list5', $list5);

        $list6=Db::table('woman')->where('art6','实心球')->limit(1)->select();
        $this -> view -> assign('list6', $list6);

        $list7=Db::table('woman')->where('art7','铅球（7.26KG）')->limit(1)->select();
        $this -> view -> assign('list7', $list7);

        $list8=Db::table('woman')->where('art8','跳远')->limit(1)->select();
        $this -> view -> assign('list8', $list8);

        $list9=Db::table('woman')->where('art9','三级跳远')->limit(1)->select();
        $this -> view -> assign('list9', $list9);

        $list10=Db::table('woman')->where('art10','跳高')->limit(1)->select();
        $this -> view -> assign('list10', $list10);

        return $this->view->fetch('time_list');
    }

    //100米成绩排名界面
    public function ranking1()
    {
        $this->view->assign('title','100米成绩排名');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art1','100米')->order('score1 asc')->limit(10)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('ranking1');
    }

    //200米成绩排名界面
    public function ranking2()
    {
        $this->view->assign('title','200米成绩排名');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art2','200米')->order('score2 asc')->limit(10)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('ranking2');
    }

    //400米成绩排名界面
    public function ranking3()
    {
        $this->view->assign('title','400米成绩排名');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art3','400米')->order('score3 asc')->limit(10)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('ranking3');
    }

    //800米成绩排名界面
    public function ranking4()
    {
        $this->view->assign('title','800米成绩排名');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art4','800米')->order('score4 asc')->limit(10)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('ranking4');
    }

    //1500米成绩排名界面
    public function ranking5()
    {
        $this->view->assign('title','1500米成绩排名');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art5','1500米')->order('score5 asc')->limit(10)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('ranking5');
    }

    //实心球成绩排名界面
    public function ranking6()
    {
        $this->view->assign('title','实心球成绩排名');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art6','实心球')->order('score6 asc')->limit(10)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('ranking6');
    }

    //铅球（7.26KG）米成绩排名界面
    public function ranking7()
    {
        $this->view->assign('title','100米成绩排名');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art7','铅球（7.26KG）')->order('score7 asc')->limit(10)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('ranking7');
    }

    //跳远成绩排名界面
    public function ranking8()
    {
        $this->view->assign('title','跳远成绩排名');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art8','跳远')->order('score8 asc')->limit(10)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('ranking8');
    }

    //三级跳远成绩排名界面
    public function ranking9()
    {
        $this->view->assign('title','三级跳远成绩排名');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art9','三级跳远')->order('score9 asc')->limit(10)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('ranking9');
    }

    //跳高成绩排名界面
    public function ranking10()
    {
        $this->view->assign('title','跳高成绩排名');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art10','跳高')->order('score10 asc')->limit(10)->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('ranking10');
    }


//100米成绩录入界面
    public function score1()
    {
        $this->view->assign('title','100米成绩录入');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art1','100米')->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('score1');
    }

    //200米成绩录入界面
    public function score2()
    {
        $this->view->assign('title','200米成绩录入');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art2','200米')->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('score2');
    }

    //400米成绩录入界面
    public function score3()
    {
        $this->view->assign('title','400米成绩录入');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art3','400米')->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('score3');
    }

    //800米成绩录入界面
    public function score4()
    {
        $this->view->assign('title','800米成绩录入');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art4','800米')->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('score4');
    }

    //1500米成绩录入界面
    public function score5()
    {
        $this->view->assign('title','1500米成绩录入');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art5','1500米')->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('score5');
    }

    //实心球成绩录入界面
    public function score6()
    {
        $this->view->assign('title','实心球成绩录入');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art6','实心球')->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('score6');
    }

    //铅球（7.26KG）米成绩录入界面
    public function score7()
    {
        $this->view->assign('title','100米成绩录入');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art7','铅球（7.26KG）')->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('score7');
    }

    //跳远成绩录入界面
    public function score8()
    {
        $this->view->assign('title','跳远成绩录入');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art8','跳远')->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('score8');
    }

    //三级跳远成绩录入界面
    public function score9()
    {
        $this->view->assign('title','三级跳远成绩录入');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('man')->where('art9','三级跳远')->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('score9');
    }

    //跳高成绩录入界面
    public function score10()
    {
        $this->view->assign('title','跳高成绩录入');
        $this->view->assign('keyword','');
        $this->view->assign('desc','');

        $list=Db::table('woman')->where('art10','跳高')->select();
        $this -> view -> assign('list', $list);

        return $this->view->fetch('score10');
    }


    //100米成绩更改界面
    public function changeScore1(Request $request)
    {
        $user_id = $request -> param('id');
        $result = WomanModel::get($user_id);
        $this->view->assign('title','成绩更改界面');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('changeScore1');
    }

    //200米成绩更改界面
    public function changeScore2(Request $request)
    {
        $user_id = $request -> param('id');
        $result = WomanModel::get($user_id);
        $this->view->assign('title','成绩更改界面');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('changeScore2');
    }

    //400米成绩更改界面
    public function changeScore3(Request $request)
    {
        $user_id = $request -> param('id');
        $result = WomanModel::get($user_id);
        $this->view->assign('title','成绩更改界面');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('changeScore3');
    }

    //800米成绩更改界面
    public function changeScore4(Request $request)
    {
        $user_id = $request -> param('id');
        $result = WomanModel::get($user_id);
        $this->view->assign('title','成绩更改界面');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('changeScore4');
    }

    //1500米成绩更改界面
    public function changeScore5(Request $request)
    {
        $user_id = $request -> param('id');
        $result = WomanModel::get($user_id);
        $this->view->assign('title','成绩更改界面');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('changeScore5');
    }

    //实心球成绩更改界面
    public function changeScore6(Request $request)
    {
        $user_id = $request -> param('id');
        $result = WomanModel::get($user_id);
        $this->view->assign('title','成绩更改界面');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('changeScore6');
    }

    //铅球（7.26KG）米成绩更改界面
    public function changeScore7(Request $request)
    {
        $user_id = $request -> param('id');
        $result = WomanModel::get($user_id);
        $this->view->assign('title','成绩更改界面');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('changeScore7');
    }

    //跳远成绩更改界面
    public function changeScore8(Request $request)
    {
        $user_id = $request -> param('id');
        $result = WomanModel::get($user_id);
        $this->view->assign('title','成绩更改界面');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('changeScore8');
    }

    //三级跳远成绩更改界面
    public function changeScore9(Request $request)
    {
        $user_id = $request -> param('id');
        $result = WomanModel::get($user_id);
        $this->view->assign('title','成绩更改界面');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('changeScore9');
    }

    //跳高成绩更改界面
    public function changeScore10(Request $request)
    {
        $user_id = $request -> param('id');
        $result = WomanModel::get($user_id);
        $this->view->assign('title','成绩更改界面');
        $this->view->assign('keywords','');
        $this->view->assign('desc','');
        $this->view->assign('user_info',$result->getData());
        return $this->view->fetch('changeScore10');
    }


//更新女运动员成绩
    public function changeScore_edit(Request $request)
    {
        //获取表单返回的数据
//        $data = $request -> param();
        $param = $request->param();

        //去掉表单中为空的数据,即没有修改的内容
        foreach ($param as $key => $value) {
            if (!empty($value)) {
                $data[$key] = $value;
            }
        }

        $condition = ['id' => $data['id']];
        $result = WomanModel::update($data, $condition);



        if (true == $result) {
            return ['status' => 1, 'message' => '更新成功'];
        } else {
            return ['status' => 0, 'message' => '更新失败,请检查'];
        }
    }
    /**
     * 项目报名情况
     */
    public function situation1()
    {
        $this->view->assign('title', '100米报名情况');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        $this->view->count = Db::table('woman')->where('art1','100米')->count();//查询数据数量

        $list = Db::table('woman')->where('art1','100米')->select();

        $this -> view -> assign('list', $list);

        return $this->view->fetch('situation1');
    }
    public function situation2()
    {
        $this->view->assign('title', '200米报名情况');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        $this->view->count = Db::table('woman')->where('art2','200米')->count();//查询数据数量

        $list = Db::table('woman')->where('art2','200米')->select();

        $this -> view -> assign('list', $list);

        return $this->view->fetch('situation2');
    }
    public function situation3()
    {
        $this->view->assign('title', '400米报名情况');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        $this->view->count = Db::table('woman')->where('art3','400米')->count();//查询数据数量

        $list = Db::table('woman')->where('art3','400米')->select();

        $this -> view -> assign('list', $list);

        return $this->view->fetch('situation3');
    }
    public function situation4()
    {
        $this->view->assign('title', '800米报名情况');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        $this->view->count = Db::table('woman')->where('art4','800米')->count();//查询数据数量

        $list = Db::table('woman')->where('art4','800米')->select();

        $this -> view -> assign('list', $list);

        return $this->view->fetch('situation4');
    }
    public function situation5()
    {
        $this->view->assign('title', '1500米报名情况');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        $this->view->count = Db::table('woman')->where('art5','1500米')->count();//查询数据数量

        $list = Db::table('woman')->where('art5','1500米')->select();

        $this -> view -> assign('list', $list);

        return $this->view->fetch('situation5');
    }
    public function situation6()
    {
        $this->view->assign('title', '实心球报名情况');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        $this->view->count = Db::table('woman')->where('art6','实心球')->count();//查询数据数量

        $list = Db::table('woman')->where('art6','实心球')->select();

        $this -> view -> assign('list', $list);

        return $this->view->fetch('situation6');
    }
    public function situation7()
    {
        $this->view->assign('title', '铅球（7.26KG）报名情况');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        $this->view->count = Db::table('woman')->where('art7','铅球（7.26KG）')->count();//查询数据数量

        $list = Db::table('woman')->where('art7','铅球（7.26KG）')->select();

        $this -> view -> assign('list', $list);

        return $this->view->fetch('situation7');
    }
    public function situation8()
    {
        $this->view->assign('title', '跳远报名情况');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        $this->view->count = Db::table('woman')->where('art8','跳远')->count();//查询数据数量

        $list = Db::table('woman')->where('art8','跳远')->select();

        $this -> view -> assign('list', $list);

        return $this->view->fetch('situation8');
    }
    public function situation9()
    {
        $this->view->assign('title', '三级跳远报名情况');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        $this->view->count = Db::table('woman')->where('art9','三级跳远')->count();//查询数据数量

        $list = Db::table('woman')->where('art9','三级跳远')->select();

        $this -> view -> assign('list', $list);

        return $this->view->fetch('situation9');
    }
    public function situation10()
    {
        $this->view->assign('title', '跳高报名情况');
        $this->view->assign('keywords', '');
        $this->view->assign('desc', '');

        $this->view->count = Db::table('woman')->where('art10','跳高')->count();//查询数据数量

        $list = Db::table('woman')->where('art10','跳高')->select();

        $this -> view -> assign('list', $list);

        return $this->view->fetch('situation10');
    }
}

